CREATE TABLE `bodega` (
  `ID_BODEGA` int(11) NOT NULL,
  `NOMBRE_BODEGA` varchar(255) DEFAULT NULL,
  `UBICACION` varchar(255) DEFAULT NULL,
  `CAPACIDAD` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_BODEGA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `carrito_compra` (
  `ID_CLIENTE` int(11) NOT NULL,
  `ID_CARRITO_COMPRA` int(11) NOT NULL,
  `ID_PEDIDO` int(11) DEFAULT NULL,
  `FECHA_CREACION` date DEFAULT NULL,
  `ESTADO` char(10) DEFAULT NULL,
  PRIMARY KEY (`ID_CLIENTE`,`ID_CARRITO_COMPRA`),
  KEY `FK_CARRITO__PEDIDO_CA_PEDIDO` (`ID_PEDIDO`),
  CONSTRAINT `FK_CARRITO__CLIENTE_C_CLIENTE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID_CLIENTE`),
  CONSTRAINT `FK_CARRITO__PEDIDO_CA_PEDIDO` FOREIGN KEY (`ID_PEDIDO`) REFERENCES `pedido` (`ID_PEDIDO`),
  CONSTRAINT `carrito_compra_ibfk_1` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID_CLIENTE`),
  CONSTRAINT `carrito_compra_ibfk_2` FOREIGN KEY (`ID_PEDIDO`) REFERENCES `pedido` (`ID_PEDIDO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `categoria_empleado` (
  `ID_CATEGORIA_EMPLEADO` int(11) NOT NULL,
  `NOMBRE_CATEGORIA` varchar(255) DEFAULT NULL,
  `SALARIO` int(11) DEFAULT NULL,
  `BENEFICIOS` varchar(255) DEFAULT NULL,
  `DESCRIPCION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_CATEGORIA_EMPLEADO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `categoria_producto` (
  `ID_CATEGORIA_PRODUCTO` int(11) NOT NULL,
  `EMBUTIDOS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_CATEGORIA_PRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `cliente` (
  `ID_CLIENTE` int(11) NOT NULL,
  `NOMBRE` varchar(255) DEFAULT NULL,
  `TELEFONO` int(11) DEFAULT NULL,
  `CEDULA` int(11) DEFAULT NULL,
  `CORREO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_CLIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `contrato` (
  `ID_CONTRARTO` int(11) NOT NULL,
  `FECHA_INICIO_CONTRATO` date DEFAULT NULL,
  `FECHA_FIN_CONTRATO` date DEFAULT NULL,
  `SUELDO` decimal(10,2) DEFAULT NULL,
  `TERMINOS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_CONTRARTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `detalle_factura` (
  `ID_DETALLE_FACTURA` int(11) NOT NULL,
  `ID_FACTURA` int(11) DEFAULT NULL,
  `ID_METODO_PAGO` int(11) DEFAULT NULL,
  `CANTIDAD_PRODUCTO` int(11) DEFAULT NULL,
  `PRECIO_UNITARIO` decimal(10,2) DEFAULT NULL,
  `SUBTOTAL` decimal(10,2) DEFAULT NULL,
  `IVA` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`ID_DETALLE_FACTURA`),
  KEY `FK_DETALLE__FACTURA_D_FACTURA` (`ID_FACTURA`),
  KEY `FK_DETALLE__RELATIONS_METODO_P` (`ID_METODO_PAGO`),
  CONSTRAINT `FK_DETALLE__FACTURA_D_FACTURA` FOREIGN KEY (`ID_FACTURA`) REFERENCES `factura` (`ID_FACTURA`),
  CONSTRAINT `FK_DETALLE__RELATIONS_METODO_P` FOREIGN KEY (`ID_METODO_PAGO`) REFERENCES `metodo_pago` (`ID_METODO_PAGO`),
  CONSTRAINT `detalle_factura_ibfk_1` FOREIGN KEY (`ID_FACTURA`) REFERENCES `factura` (`ID_FACTURA`),
  CONSTRAINT `detalle_factura_ibfk_2` FOREIGN KEY (`ID_METODO_PAGO`) REFERENCES `metodo_pago` (`ID_METODO_PAGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `detalle_producto` (
  `ID_DETALLE_PRODUCTO` int(11) NOT NULL,
  `COMPOSICION` varchar(255) DEFAULT NULL,
  `FECHA_ELABORACION` date DEFAULT NULL,
  `FECHA_CADUCIDAD` date DEFAULT NULL,
  `TAMANO` varchar(255) DEFAULT NULL,
  `PESO` varchar(255) DEFAULT NULL,
  `MODELO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_DETALLE_PRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `detallefactura_producto` (
  `ID_PRODUCTO` int(11) NOT NULL,
  `ID_DETALLE_FACTURA` int(11) NOT NULL,
  PRIMARY KEY (`ID_PRODUCTO`,`ID_DETALLE_FACTURA`),
  KEY `FK_DETALLEF_RELATIONS_DETALLE_` (`ID_DETALLE_FACTURA`),
  CONSTRAINT `FK_DETALLEF_RELATIONS_DETALLE_` FOREIGN KEY (`ID_DETALLE_FACTURA`) REFERENCES `detalle_factura` (`ID_DETALLE_FACTURA`),
  CONSTRAINT `FK_DETALLEF_RELATIONS_PRODUCTO` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `producto` (`ID_PRODUCTO`),
  CONSTRAINT `detallefactura_producto_ibfk_1` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `producto` (`ID_PRODUCTO`),
  CONSTRAINT `detallefactura_producto_ibfk_2` FOREIGN KEY (`ID_DETALLE_FACTURA`) REFERENCES `detalle_factura` (`ID_DETALLE_FACTURA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `direccion_entrega` (
  `ID_DIRECCION_ENTREGA` int(11) NOT NULL,
  `NUMERO_TELEFONO` int(11) DEFAULT NULL,
  `DIRECCION_DE_ENVIO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_DIRECCION_ENTREGA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `empleado` (
  `ID_EMPLEADO` int(11) NOT NULL,
  `ID_CATEGORIA_EMPLEADO` int(11) DEFAULT NULL,
  `ID_CONTRATO` int(11) NOT NULL,
  `NOMBRE_EMPLEADO` varchar(255) DEFAULT NULL,
  `FECHA_CONTRATACION` date DEFAULT NULL,
  `FECHA_NACIMIENTO` date DEFAULT NULL,
  `CONTACTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_EMPLEADO`),
  KEY `FK_EMPLEADO_CATEGORIA_CATEGORI` (`ID_CATEGORIA_EMPLEADO`),
  KEY `FK_EMPLEADO_RELATIONS_CONTRATO` (`ID_CONTRATO`),
  CONSTRAINT `FK_EMPLEADO_CATEGORIA_CATEGORI` FOREIGN KEY (`ID_CATEGORIA_EMPLEADO`) REFERENCES `categoria_empleado` (`ID_CATEGORIA_EMPLEADO`),
  CONSTRAINT `FK_EMPLEADO_RELATIONS_CONTRATO` FOREIGN KEY (`ID_CONTRATO`) REFERENCES `contrato` (`ID_CONTRARTO`),
  CONSTRAINT `empleado_ibfk_1` FOREIGN KEY (`ID_CATEGORIA_EMPLEADO`) REFERENCES `categoria_empleado` (`ID_CATEGORIA_EMPLEADO`),
  CONSTRAINT `empleado_ibfk_2` FOREIGN KEY (`ID_CONTRATO`) REFERENCES `contrato` (`ID_CONTRARTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `factura` (
  `ID_FACTURA` int(11) NOT NULL,
  `ID_CLIENTE` int(11) DEFAULT NULL,
  `ID_PROMOCION` int(11) DEFAULT NULL,
  `ID_EMPLEADO` int(11) DEFAULT NULL,
  `FECHA_EMISION` date DEFAULT NULL,
  `TOTAL` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`ID_FACTURA`),
  KEY `FK_FACTURA_CLIENTE_F_CLIENTE` (`ID_CLIENTE`),
  KEY `FK_FACTURA_EMPLEADO__EMPLEADO` (`ID_EMPLEADO`),
  KEY `FK_FACTURA_PROMOCION_PROMOCIO` (`ID_PROMOCION`),
  CONSTRAINT `FK_FACTURA_CLIENTE_F_CLIENTE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID_CLIENTE`),
  CONSTRAINT `FK_FACTURA_EMPLEADO__EMPLEADO` FOREIGN KEY (`ID_EMPLEADO`) REFERENCES `empleado` (`ID_EMPLEADO`),
  CONSTRAINT `FK_FACTURA_PROMOCION_PROMOCIO` FOREIGN KEY (`ID_PROMOCION`) REFERENCES `promociones` (`ID_PROMOCION`),
  CONSTRAINT `factura_ibfk_1` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID_CLIENTE`),
  CONSTRAINT `factura_ibfk_2` FOREIGN KEY (`ID_PROMOCION`) REFERENCES `promociones` (`ID_PROMOCION`),
  CONSTRAINT `factura_ibfk_3` FOREIGN KEY (`ID_EMPLEADO`) REFERENCES `empleado` (`ID_EMPLEADO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `metodo_pago` (
  `ID_METODO_PAGO` int(11) NOT NULL,
  `TARJETA` tinyint(1) DEFAULT NULL,
  `EFECTIVO` tinyint(1) DEFAULT NULL,
  `TRANSFERENCIA` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID_METODO_PAGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `pasillo` (
  `ID_PASILLO` int(11) NOT NULL,
  `NUM_PASILLO` int(11) DEFAULT NULL,
  `NOMBRE_PASILLO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_PASILLO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `pedido` (
  `ID_PEDIDO` int(11) NOT NULL,
  `ID_DIRECCION_ENTREGA` int(11) DEFAULT NULL,
  `ESTADO_ENTREGA` varchar(255) DEFAULT NULL,
  `FECHA_ENVIO` date DEFAULT NULL,
  PRIMARY KEY (`ID_PEDIDO`),
  KEY `FK_PEDIDO_DIRECCION_DIRECCIO` (`ID_DIRECCION_ENTREGA`),
  CONSTRAINT `FK_PEDIDO_DIRECCION_DIRECCIO` FOREIGN KEY (`ID_DIRECCION_ENTREGA`) REFERENCES `direccion_entrega` (`ID_DIRECCION_ENTREGA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `producto` (
  `ID_PRODUCTO` int(11) NOT NULL,
  `ID_PROVEEDOR` int(11) DEFAULT NULL,
  `ID_CATEGORIA_PRODUCTO` int(11) DEFAULT NULL,
  `NOMBRE_PRODUCTO` varchar(255) DEFAULT NULL,
  `DESCRIPCION_PRODUCTO` varchar(255) DEFAULT NULL,
  `PRECIO_PRODUCTO` decimal(10,2) DEFAULT NULL,
  `STOCK` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_PRODUCTO`),
  KEY `FK_PRODUCTO_RELATIONS_PROVEEDO` (`ID_PROVEEDOR`),
  KEY `FK_PRODUCTO_RELATIONS_CATEGORI` (`ID_CATEGORIA_PRODUCTO`),
  CONSTRAINT `FK_PRODUCTO_RELATIONS_CATEGORI` FOREIGN KEY (`ID_CATEGORIA_PRODUCTO`) REFERENCES `categoria_producto` (`ID_CATEGORIA_PRODUCTO`),
  CONSTRAINT `FK_PRODUCTO_RELATIONS_PROVEEDO` FOREIGN KEY (`ID_PROVEEDOR`) REFERENCES `proveedor` (`ID_PROVEEDOR`),
  CONSTRAINT `producto_ibfk_1` FOREIGN KEY (`ID_PROVEEDOR`) REFERENCES `proveedor` (`ID_PROVEEDOR`),
  CONSTRAINT `producto_ibfk_2` FOREIGN KEY (`ID_CATEGORIA_PRODUCTO`) REFERENCES `categoria_producto` (`ID_CATEGORIA_PRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `producto_bodega` (
  `ID_BODEGA` int(11) NOT NULL,
  `ID_PRODUCTO` int(11) NOT NULL,
  `CANTIDAD_PRODUCTOBODEGA` int(11) DEFAULT NULL,
  `FECHA_ENTRADA_BODEGA` date DEFAULT NULL,
  `FECHA_SALIDA` date DEFAULT NULL,
  PRIMARY KEY (`ID_BODEGA`,`ID_PRODUCTO`),
  KEY `FK_PRODUCTO_RELATIONS_PRODUCTO` (`ID_PRODUCTO`),
  CONSTRAINT `FK_PRODUCTO_RELATIONS_BODEGA` FOREIGN KEY (`ID_BODEGA`) REFERENCES `bodega` (`ID_BODEGA`),
  CONSTRAINT `FK_PRODUCTO_RELATIONS_PRODUCTO` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `producto` (`ID_PRODUCTO`),
  CONSTRAINT `producto_bodega_ibfk_1` FOREIGN KEY (`ID_BODEGA`) REFERENCES `bodega` (`ID_BODEGA`),
  CONSTRAINT `producto_bodega_ibfk_2` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `producto` (`ID_PRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `promociones` (
  `ID_PROMOCION` int(11) NOT NULL,
  `TIPO_PROM` varchar(255) DEFAULT NULL,
  `FECHA_INICIO` date DEFAULT NULL,
  `FECHA_FIN` date DEFAULT NULL,
  PRIMARY KEY (`ID_PROMOCION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `proveedor` (
  `ID_PROVEEDOR` int(11) NOT NULL,
  `NOMBRE_PROVEEDOR` varchar(255) DEFAULT NULL,
  `CEDULA_PROVEEDOR` int(11) DEFAULT NULL,
  `NUMERO_TELEFONO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_PROVEEDOR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


