
    DELIMITER $$
    CREATE PROCEDURE pedido_insert(IN p_ID_PEDIDO int(11), IN p_ID_DIRECCION_ENTREGA int(11), IN p_ESTADO_ENTREGA varchar(255), IN p_FECHA_ENVIO date)
    BEGIN
        INSERT INTO pedido (ID_PEDIDO, ID_DIRECCION_ENTREGA, ESTADO_ENTREGA, FECHA_ENVIO) VALUES (p_ID_PEDIDO, p_ID_DIRECCION_ENTREGA, p_ESTADO_ENTREGA, p_FECHA_ENVIO);
    END$$
    DELIMITER ;
    

    DELIMITER $$
    CREATE PROCEDURE pedido_select()
    BEGIN
        SELECT * FROM pedido;
    END$$
    DELIMITER ;
    

    DELIMITER $$
    CREATE PROCEDURE pedido_update(IN p_ID_DIRECCION_ENTREGA int(11), IN p_ESTADO_ENTREGA varchar(255), IN p_FECHA_ENVIO date, IN p_ID_PEDIDO INT)
    BEGIN
        UPDATE pedido SET ID_DIRECCION_ENTREGA = p_ID_DIRECCION_ENTREGA, ESTADO_ENTREGA = p_ESTADO_ENTREGA, FECHA_ENVIO = p_FECHA_ENVIO WHERE ID_PEDIDO = p_ID_PEDIDO;
    END$$
    DELIMITER ;
    

    DELIMITER $$
    CREATE PROCEDURE pedido_delete(IN p_ID_PEDIDO INT)
    BEGIN
        DELETE FROM pedido WHERE ID_PEDIDO = p_ID_PEDIDO;
    END$$
    DELIMITER ;
    