
    DELIMITER $$
    CREATE PROCEDURE proveedor_insert(IN p_ID_PROVEEDOR int(11), IN p_NOMBRE_PROVEEDOR varchar(255), IN p_CEDULA_PROVEEDOR int(11), IN p_NUMERO_TELEFONO int(11))
    BEGIN
        INSERT INTO proveedor (ID_PROVEEDOR, NOMBRE_PROVEEDOR, CEDULA_PROVEEDOR, NUMERO_TELEFONO) VALUES (p_ID_PROVEEDOR, p_NOMBRE_PROVEEDOR, p_CEDULA_PROVEEDOR, p_NUMERO_TELEFONO);
    END$$
    DELIMITER ;
    

    DELIMITER $$
    CREATE PROCEDURE proveedor_select()
    BEGIN
        SELECT * FROM proveedor;
    END$$
    DELIMITER ;
    

    DELIMITER $$
    CREATE PROCEDURE proveedor_update(IN p_NOMBRE_PROVEEDOR varchar(255), IN p_CEDULA_PROVEEDOR int(11), IN p_NUMERO_TELEFONO int(11), IN p_ID_PROVEEDOR INT)
    BEGIN
        UPDATE proveedor SET NOMBRE_PROVEEDOR = p_NOMBRE_PROVEEDOR, CEDULA_PROVEEDOR = p_CEDULA_PROVEEDOR, NUMERO_TELEFONO = p_NUMERO_TELEFONO WHERE ID_PROVEEDOR = p_ID_PROVEEDOR;
    END$$
    DELIMITER ;
    

    DELIMITER $$
    CREATE PROCEDURE proveedor_delete(IN p_ID_PROVEEDOR INT)
    BEGIN
        DELETE FROM proveedor WHERE ID_PROVEEDOR = p_ID_PROVEEDOR;
    END$$
    DELIMITER ;
    